import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import logo from "../public/liveblocks.svg";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="min-h-screen bg-gradient-to-b from-black via-black to-[#220006] relative flex justify-center items-center">
        <Image src={logo} />
        <div className="fixed w-full h-full -bottom-1/2 -left-1/2 bg-rose-500 rounded-full blur-3xl opacity-5" />
        <div className="fixed w-full h-full -bottom-1/2 -right-1/2 bg-orange-500 rounded-full blur-3xl opacity-5" />
      </main>

    </div>
  )
}

export default Home
