packages:
  - "shared/*"
  - "packages/*"
  - "!packages/liveblocks-server"
  - "!packages/liveblocks-python"
  - "!packages/liveblocks-python-codegen"
  - "tools/*"
  - "!tools/liveblocks-cli"
  - "e2e/next-ai-kitchen-sink"
  - "e2e/next-react-flow-kitchen-sink"
  - "e2e/next-sandbox"
  - "e2e/node-sandbox"

allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  "@tailwindcss/oxide": true
  "esbuild": true
  "lmdb": true
  "msgpackr-extract": true
  "msw": true
  "sharp": true
