name: "Docs Request for an Update or Improvement"
description: A request to update or improve Liveblocks documentation
title: "Docs: "
labels:
  - "template: documentation"
body:
  - type: textarea
    attributes:
      label: What is the improvement or update you wish to see?
      description:
        "Example: I would like to see more examples of how to leverage the
        Next.js authentification. Or, the Next.js authentification guide is
        missing information."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is there any context that might help us understand?
      description:
        A clear description of any added context that might help us understand.
    validations:
      required: true
  - type: input
    attributes:
      label: Does the docs page already exist? Please link to it.
      description:
        "Example: https://liveblocks.io/docs/guides/authentication/next-js"
    validations:
      required: false
