// Unlike `icons/index.ts` which exports all icons privately, this file
// is meant to export all icons which should be publically available
// via `import { Icon } from "@liveblocks/react-ui"` and `<Icon.* />`.

export {
  ArrowCornerDownRightIcon as ArrowCornerDownRight,
  ArrowCornerUpRightIcon as ArrowCornerUpRight,
  AttachmentIcon as Attachment,
  BlockquoteIcon as Blockquote,
  BoldIcon as Bold,
  CheckIcon as Check,
  CodeIcon as Code,
  CommentIcon as Comment,
  CrossIcon as Cross,
  EllipsisIcon as Ellipsis,
  EmojiIcon as Emoji,
  H1Icon as H1,
  H2Icon as H2,
  H3Icon as H3,
  ItalicIcon as Italic,
  LengthenIcon as Lengthen,
  ListOrderedIcon as ListOrdered,
  ListUnorderedIcon as ListUnordered,
  MentionIcon as Mention,
  QuestionMarkIcon as QuestionMark,
  RedoIcon as Redo,
  SendIcon as Send,
  ShortenIcon as Shorten,
  SparklesIcon as Sparkles,
  SparklesTextIcon as SparklesText,
  StrikethroughIcon as Strikethrough,
  TextIcon as Text,
  TranslateIcon as Translate,
  UnderlineIcon as Underline,
  UndoIcon as Undo,
  WarningIcon as Warning,
} from "./icons";
