import * as THREE from "three";
import { GLTF } from "three-stdlib";

export type FurnitureModels = GLTF & {
  nodes: {
    table_1: THREE.Mesh;
    table_2: THREE.Mesh;
    tableChair1_1: THREE.Mesh;
    tableChair1_2: THREE.Mesh;
    tableChair2_1: THREE.Mesh;
    tableChair2_2: THREE.Mesh;
    tableChair3_1: THREE.Mesh;
    tableChair3_2: THREE.Mesh;
    tableChair4_1: THREE.Mesh;
    tableChair4_2: THREE.Mesh;
    tableGround: THREE.Mesh;
    tableLamp_1: THREE.Mesh;
    tableLamp_2: THREE.Mesh;
    television_1: THREE.Mesh;
    television_2: THREE.Mesh;
    televisionCabinet_1: THREE.Mesh;
    televisionCabinet_2: THREE.Mesh;
    televisionGround: THREE.Mesh;
    televisionSpeaker1_1: THREE.Mesh;
    televisionSpeaker1_2: THREE.Mesh;
    televisionSpeaker2_1: THREE.Mesh;
    televisionSpeaker2_2: THREE.Mesh;
    lamp_1: THREE.Mesh;
    lamp_2: THREE.Mesh;
    lampGround: THREE.Mesh;
    sofa_1: THREE.Mesh;
    sofa_2: THREE.Mesh;
    sofaGround: THREE.Mesh;
    sofaPillow: THREE.Mesh;
    sofaPillowLong: THREE.Mesh;
    plant_1: THREE.Mesh;
    plant_2: THREE.Mesh;
    plant_3: THREE.Mesh;
    plantGround: THREE.Mesh;
    coffeeTable_1: THREE.Mesh;
    coffeeTable_2: THREE.Mesh;
    coffeeTableGround: THREE.Mesh;
    coffeeTablePlant1_1: THREE.Mesh;
    coffeeTablePlant1_2: THREE.Mesh;
    coffeeTablePlant2_1: THREE.Mesh;
    coffeeTablePlant2_2: THREE.Mesh;
    armchair_1: THREE.Mesh;
    armchair_2: THREE.Mesh;
    armchairGround: THREE.Mesh;
    armchairPillow: THREE.Mesh;
  };
  materials: {
    wood: THREE.MeshPhysicalMaterial;
    tableFabric: THREE.MeshPhysicalMaterial;
    metalDark: THREE.MeshPhysicalMaterial;
    televisionScreen: THREE.MeshStandardMaterial;
    metalMedium: THREE.MeshPhysicalMaterial;
    metal: THREE.MeshPhysicalMaterial;
    lamp: THREE.MeshPhysicalMaterial;
    sofaFabric: THREE.MeshPhysicalMaterial;
    woodDark: THREE.MeshPhysicalMaterial;
    plant: THREE.MeshPhysicalMaterial;
    glass: THREE.MeshPhysicalMaterial;
    armchairFabric: THREE.MeshPhysicalMaterial;
  };
};
