// Interface automatically generated by schemas-to-ts

import { User, User_Plain } from "./User";
import { AdminPanelRelationPropertyModification } from "./AdminPanelRelationPropertyModification";

export interface Article {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    Title: string;
    Description: string;
    Content: string;
    Date: Date;
    authors?: { data: User[] };
    Slug: string;
  };
}
export interface Article_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title: string;
  Description: string;
  Content: string;
  Date: Date;
  authors?: User_Plain[];
  Slug: string;
}

export interface Article_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title: string;
  Description: string;
  Content: string;
  Date: Date;
  authors?: number[];
  Slug: string;
}

export interface Article_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title: string;
  Description: string;
  Content: string;
  Date: Date;
  authors?: AdminPanelRelationPropertyModification<User_Plain>;
  Slug: string;
}
