// Interface automatically generated by schemas-to-ts

export interface Marketing {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    BlogTitle: string;
    BlogDescription: string;
  };
}
export interface Marketing_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  BlogTitle: string;
  BlogDescription: string;
}

export interface Marketing_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  BlogTitle: string;
  BlogDescription: string;
}

export interface Marketing_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  BlogTitle: string;
  BlogDescription: string;
}
