import { ReactNode, useState } from "react";
import Head from 'next/head'
import Image from 'next/image'
import logo from "../public/liveblocks.svg";
import iconKey from "../public/icon-key.svg";
import iconChat from "../public/icon-chat.svg";
import iconDocs from "../public/icon-docs.svg";
import iconGithub from "../public/icon-github.svg";
import Link from "next/link";

const cards = [
  {
    title: "Get your API key",
    icon: iconKey,
    content: <>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do.</>
  },
  {
    title: "Get your API key",
    icon: iconDocs,
    content: <>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do.</>
  },
  {
    title: "Get your API key",
    icon: iconGithub,
    content: <>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do.</>
  },
  {
    title: "Get support on Discord",
    icon: iconChat,
    content: <>Join our discord server to share projects you{"'"}ve built and find support.</>
  }
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="min-h-screen bg-gradient-to-b from-white via-white to-[#FEFBFC] relative flex flex-col justify-start items-center isolate">
        <div className="mt-10" >
          <Image alt="Liveblocks logo" src={logo} />
        </div>
        <div className="mt-32 grid grid-cols-2 max-w-screen-md gap-5">
          {cards.map(({ title, icon, content }) => (
            <Card key={title} title={title} icon={icon}>
              {content}
            </Card>
          ))}
        </div>

        <div>
          <CreateRoom />
        </div>

        <div className="pointer-events-none -z-10 opacity-50">
          <div className="fixed w-full h-full -bottom-1/2 -left-1/2 bg-rose-500 rounded-full blur-3xl opacity-5" />
          <div className="fixed w-full h-full -bottom-1/2 -right-1/2 bg-orange-500 rounded-full blur-3xl opacity-5" />
        </div>
      </main>

    </div>
  );
}


function Card({ children, title, icon }: { children: ReactNode, title: string, icon: string }) {
  return (
    <div className="bg-gray-50 p-6 rounded-2xl">
      <div className="bg-white rounded-xl w-14 h-14 p-3 shadow-lg shadow-orange-500/20">
        <Image alt={title} src={icon} />
      </div>
      <div className="text-lg font-medium text-black mt-5">
        {title}
      </div>
      <div className="text-gray-600 mt-0.5">
        {children}
      </div>
    </div>
  );
}

const links = {
  basic: { text: "Basic room", href: "/basic" },
  canvas: { text: "Interactive canvas", href: "/canvas" },
};

function CreateRoom() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [selected, setSelected] = useState<keyof typeof links>("basic");

  return (
    <div className="mt-40 relative">
      {menuOpen ? (
        <div className="absolute bottom-full mb-4 bg-white shadow-xl p-3 rounded-xl">
          {Object.entries(links).map(([key, { text, href }]) => (
            <Link key={key} href={href}>
              <a className="whitespace-nowrap px-3 py-1.5 hover:bg-gray-100 block rounded-lg transition-colors">
                {text}
              </a>
            </Link>
          ))}
        </div>
      ) : null}
      <button
        className="text-white bg-gray-800 py-3 px-6 rounded-xl flex justify-center items-center"
        onClick={() => setMenuOpen(!menuOpen)}
      >
        <span className="text-gray-500 mr-2 text-2xl -mt-1">+</span> Create room
      </button>
    </div>
  );
}
