#!/usr/bin/env node
/**
 * Checks all internal links in docs/pages, guides/pages, and tutorial for
 * broken targets and broken #anchors. Runs fully offline against the local
 * checkout — no network access needed.
 *
 * Usage: node scripts/check-docs-links.mts [--verbose]
 *
 * What is checked:
 *   - /docs/*            → must resolve to docs/pages/*.mdx (or /index.mdx),
 *                          or be registered in docs/routes.json (generated
 *                          pages like /docs/api-reference/rest-api-endpoints)
 *   - /docs/guides/*     → must resolve to guides/pages/*.mdx
 *   - /docs/tutorial/*   → must resolve to tutorial/* (step's guide.mdx)
 *   - /guides/*          → flagged: non-canonical, should be /docs/guides/*
 *   - #anchors           → must match a heading in the target file, using the
 *                          same slug rules as the website: case is PRESERVED,
 *                          backticks and "?" are stripped, spaces become "-",
 *                          and explicit ids ("### Heading [#my-id]") win
 *   - other /… paths     → website pages outside this repo (e.g. /blog);
 *                          not verifiable locally, listed with --verbose
 *   - http(s)/mailto     → skipped
 */

import * as fs from "node:fs";
import * as path from "node:path";

const ROOT = path.join(import.meta.dirname, "..");
const VERBOSE = process.argv.includes("--verbose");

const LINK_RE = /\[[^\]]*\]\(([^)\s]+)\)/g;
const HREF_RE = /href="([^"]+)"/g;
const HEADING_RE = /^#{1,6}\s+(.*)$/gm;

function listMdxFiles(dir: string): string[] {
  return fs
    .readdirSync(dir, { recursive: true, encoding: "utf8" })
    .filter((f) => f.endsWith(".mdx"))
    .map((f) => path.join(dir, f))
    .sort();
}

const FILES = [
  ...listMdxFiles(path.join(ROOT, "docs/pages")),
  ...listMdxFiles(path.join(ROOT, "guides/pages")),
  ...listMdxFiles(path.join(ROOT, "tutorial")),
];

// Category hub pages generated by the website (e.g. liveblocks.io/docs/
// get-started/comments lists all Comments get-started guides). These have no
// .mdx file and no routes.json entry, but are valid link targets.
const GENERATED_HUB_PAGES = new Set([
  "/docs/get-started/comments",
  "/docs/get-started/notifications",
  "/docs/get-started/multiplayer",
  "/docs/get-started/ai-collaboration",
  "/docs/get-started/ai-copilots",
]);

// Any route registered in routes.json (path or href) is a valid link target,
// even when it has no backing .mdx file (generated pages, redirects).
const routesRaw = fs.readFileSync(path.join(ROOT, "docs/routes.json"), "utf8");
const REGISTERED_ROUTES = new Set(
  [...routesRaw.matchAll(/"(?:path|href)": "(\/[^"]+)"/g)].map(
    (m) => "/docs" + m[1]
  )
);

/**
 * Mirrors the website's heading→anchor slug algorithm. Notably, case is
 * preserved ("### Typing your data" → #Typing-your-data).
 */
function slugify(text: string): string {
  return text
    .replace(/`/g, "")
    .replace(/\[#[^\]]+\]/g, "") // explicit id marker
    .replace(/\[@[^\]]+\]/g, "") // badge marker
    .replace(/\?/g, "")
    .trim()
    .replace(/\s+/g, "-");
}

const anchorCache = new Map<string, Set<string>>();

function getAnchors(file: string): Set<string> {
  const cached = anchorCache.get(file);
  if (cached) return cached;

  const anchors = new Set<string>();
  const content = fs.readFileSync(file, "utf8");
  for (const m of content.matchAll(HEADING_RE)) {
    const heading = m[1];
    const explicit = heading.match(/\[#([^\]]+)\]/);
    if (explicit) anchors.add(explicit[1]);
    anchors.add(slugify(heading));
  }
  // Explicit id="..." attributes in JSX also produce anchors.
  for (const m of content.matchAll(/id="([^"]+)"/g)) {
    anchors.add(m[1]);
  }
  anchorCache.set(file, anchors);
  return anchors;
}

const GUIDES_INDEX = Symbol("guides index");

/** Resolves a /docs/... URL to a local .mdx file, if one exists. */
function resolveDocs(url: string): string | typeof GUIDES_INDEX | null {
  const rel = url.slice("/docs".length).replace(/^\/+|\/+$/g, "");
  if (rel === "") return path.join(ROOT, "docs/pages/index.mdx");
  // Guides are served under /docs/guides/* but live in guides/pages/*.
  if (rel === "guides") return GUIDES_INDEX;
  if (rel.startsWith("guides/")) {
    const full = path.join(
      ROOT,
      `guides/pages/${rel.slice("guides/".length)}.mdx`
    );
    return fs.existsSync(full) ? full : null;
  }
  // Tutorial steps are served under /docs/tutorial/* but live in tutorial/*,
  // with the page content in each step's guide.mdx.
  if (rel.startsWith("tutorial/")) {
    const full = path.join(
      ROOT,
      `tutorial/${rel.slice("tutorial/".length)}/guide.mdx`
    );
    return fs.existsSync(full) ? full : null;
  }
  for (const cand of [`docs/pages/${rel}.mdx`, `docs/pages/${rel}/index.mdx`]) {
    const full = path.join(ROOT, cand);
    if (fs.existsSync(full)) return full;
  }
  return null;
}

const issues: string[] = [];
const websitePaths = new Map<string, number>();

for (const file of FILES) {
  const fname = path.relative(ROOT, file);
  const lines = fs.readFileSync(file, "utf8").split("\n");

  lines.forEach((line, i) => {
    const lineno = i + 1;
    const urls = [
      ...[...line.matchAll(LINK_RE)].map((m) => m[1]),
      ...[...line.matchAll(HREF_RE)].map((m) => m[1]),
    ];

    for (let url of urls) {
      if (/^(https?:|mailto:)/.test(url)) continue;

      url = url.split("?")[0];
      let anchor: string | null = null;
      const hashIdx = url.indexOf("#");
      if (hashIdx !== -1) {
        anchor = url.slice(hashIdx + 1);
        url = url.slice(0, hashIdx);
      }

      if (url === "") {
        // "#/file.ts" links in tutorials open a file in the embedded code
        // editor; they are not heading anchors.
        if (anchor?.startsWith("/")) continue;
        // Same-page anchor.
        if (anchor && !getAnchors(file).has(anchor)) {
          issues.push(
            `Anchor: #${anchor}
  File: ${fname}:${lineno}
`
          );
        }
      } else if (url.startsWith("/docs")) {
        const target = resolveDocs(url);
        if (target === GUIDES_INDEX) continue;
        if (target === null) {
          if (REGISTERED_ROUTES.has(url) || GENERATED_HUB_PAGES.has(url))
            continue;
          issues.push(
            `  Link: ${url}${anchor ? "#" + anchor : ""}
  File: ${fname}:${lineno}
`
          );
        } else if (anchor && !getAnchors(target).has(anchor)) {
          issues.push(
            `Anchor: #${anchor}
  Link: ${url}${anchor ? "#" + anchor : ""}
  File: ${fname}:${lineno}
`
          );
        }
      } else if (url.startsWith("/guides")) {
        issues.push(
          `Prefix: ${url} (should be /docs${url})
  File: ${fname}:${lineno}
`
        );
      } else if (url.startsWith("/")) {
        // Pages on liveblocks.io outside this repo (e.g. /blog, /examples);
        // cannot be verified locally.
        websitePaths.set(url, (websitePaths.get(url) ?? 0) + 1);
      }
    }
  });
}

console.log(`Checked docs links in ${FILES.length} files.`);

if (VERBOSE && websitePaths.size > 0) {
  console.log(
    `\n${websitePaths.size} distinct website (non-docs) paths, not verified:`
  );
  for (const [url, count] of [...websitePaths].sort()) {
    console.log(`  ${String(count).padStart(4)}x ${url}`);
  }
}

if (issues.length > 0) {
  console.error(`\n❌ ${issues.length} broken link(s) found:\n`);
  for (const issue of issues) {
    console.error(issue);
  }
  process.exit(1);
} else {
  console.log("✅ No broken internal links found");
}
