/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        surface: "rgb(var(--color-surface) / <alpha-value>)",
        "surface-hover": "rgb(var(--color-surface-hover) / <alpha-value>)",
        "surface-elevated":
          "rgb(var(--color-surface-elevated) / <alpha-value>)",
        border: "rgb(var(--color-border) / <alpha-value>)",
        "border-contrasted":
          "rgb(var(--color-border-contrasted) / <alpha-value>)",
        text: "rgb(var(--color-text) / <alpha-value>)",
        "text-light": "rgb(var(--color-text-light) / <alpha-value>)",
        "text-lighter": "rgb(var(--color-text-lighter) / <alpha-value>)",
        "text-lightest": "rgb(var(--color-text-lightest) / <alpha-value>)",
        accent: "rgb(var(--color-accent) / <alpha-value>)",
        red: "rgb(var(--color-red) / <alpha-value>)",
      },
      spacing: {
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        7: "var(--space-7)",
        8: "var(--space-8)",
        9: "var(--space-9)",
        10: "var(--space-10)",
        11: "var(--space-11)",
        12: "var(--space-12)",
        13: "var(--space-13)",
        14: "var(--space-14)",
        15: "var(--space-15)",
        16: "var(--space-16)",
        17: "var(--space-17)",
        18: "var(--space-18)",
        19: "var(--space-19)",
        20: "var(--space-20)",
        21: "var(--space-21)",
        22: "var(--space-22)",
        23: "var(--space-23)",
        24: "var(--space-24)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        DEFAULT: "var(--radius)",
        lg: "var(--radius-lg)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        DEFAULT: "var(--shadow)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
      },
      fontSize: {
        "2xs": "var(--size-2xs)",
        xs: "var(--size-xs)",
        sm: "var(--size-sm)",
        base: "var(--size)",
        lg: "var(--size-lg)",
        xl: "var(--size-xl)",
        "2xl": "var(--size-2xl)",
        "3xl": "var(--size-3xl)",
        "4xl": "var(--size-4xl)",
      },
      transitionDuration: {
        DEFAULT: "var(--transition)",
      },
    },
  },
  plugins: [],
};
