/**
 * NOTE:
 * This file is AUTOGENERATED!
 *
 * Do not update it manually.
 */

import type {
  BaseUserMeta,
  BroadcastOptions,
  History,
  Json,
  JsonObject,
  LiveList,
  LiveMap,
  LiveObject,
  Lson,
  LsonObject,
  Others,
  Room,
  User,
} from "@liveblocks/client";
import { deprecate } from "@liveblocks/client/internal";

import type { RoomProviderProps } from "./factory";
import { createRoomContext } from "./factory";

const _hooks = createRoomContext("__legacy" as any);

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `RoomProvider` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function RoomProvider<
  TPresence extends JsonObject,
  TStorage extends LsonObject
>(props: RoomProviderProps<TPresence, TStorage>) {
  deprecate(
    "Please use `createRoomContext()` instead of importing `RoomProvider` from `@liveblocks/react` directly. See https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details."
  );
  return _hooks.RoomProvider(props);
}

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useBatch` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useBatch(): (callback: () => void) => void {
  deprecate(
    "Please use `createRoomContext()` instead of importing `useBatch` from `@liveblocks/react` directly. See https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details."
  );
  return _hooks.useBatch();
}

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useBroadcastEvent` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useBroadcastEvent<TRoomEvent extends Json>(): (
  event: TRoomEvent,
  options?: BroadcastOptions
) => void {
  deprecate(
    "Please use `createRoomContext()` instead of importing `useBroadcastEvent` from `@liveblocks/react` directly. See https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details."
  );
  return _hooks.useBroadcastEvent() as unknown as (
    event: TRoomEvent,
    options?: BroadcastOptions
  ) => void;
}

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useErrorListener` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useErrorListener(callback: (err: Error) => void): void {
  deprecate(
    "Please use `createRoomContext()` instead of importing `useErrorListener` from `@liveblocks/react` directly. See https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details."
  );
  return _hooks.useErrorListener(callback);
}

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useEventListener` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useEventListener<TRoomEvent extends Json>(
  callback: (eventData: { connectionId: number; event: TRoomEvent }) => void
): void {
  deprecate(
    "Please use `createRoomContext()` instead of importing `useEventListener` from `@liveblocks/react` directly. See https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details."
  );
  return _hooks.useEventListener(callback as any);
}

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useHistory` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useHistory(): History {
  deprecate(
    "Please use `createRoomContext()` instead of importing `useHistory` from `@liveblocks/react` directly. See https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details."
  );
  return _hooks.useHistory();
}

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useMyPresence` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useMyPresence<TPresence extends JsonObject>(): [
  TPresence,
  (overrides: Partial<TPresence>, options?: { addToHistory: boolean }) => void
] {
  deprecate(
    "Please use `createRoomContext()` instead of importing `useMyPresence` from `@liveblocks/react` directly. See https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details."
  );
  return _hooks.useMyPresence() as unknown as [
    TPresence,
    (overrides: Partial<TPresence>, options?: { addToHistory: boolean }) => void
  ];
}

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useOthers` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useOthers<
  TPresence extends JsonObject,
  TUserMeta extends BaseUserMeta
>(): Others<TPresence, TUserMeta> {
  deprecate(
    "Please use `createRoomContext()` instead of importing `useOthers` from `@liveblocks/react` directly. See https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details."
  );
  return _hooks.useOthers() as unknown as Others<TPresence, TUserMeta>;
}

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useRedo` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useRedo(): () => void {
  deprecate(
    "Please use `createRoomContext()` instead of importing `useRedo` from `@liveblocks/react` directly. See https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details."
  );
  return _hooks.useRedo();
}

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useRoom` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useRoom<
  TPresence extends JsonObject,
  TStorage extends LsonObject,
  TUserMeta extends BaseUserMeta,
  TRoomEvent extends Json
>(): Room<TPresence, TStorage, TUserMeta, TRoomEvent> {
  deprecate(
    "Please use `createRoomContext()` instead of importing `useRoom` from `@liveblocks/react` directly. See https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details."
  );
  return _hooks.useRoom() as unknown as Room<
    TPresence,
    TStorage,
    TUserMeta,
    TRoomEvent
  >;
}

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useSelf` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useSelf<
  TPresence extends JsonObject,
  TUserMeta extends BaseUserMeta
>(): User<TPresence, TUserMeta> | null {
  deprecate(
    "Please use `createRoomContext()` instead of importing `useSelf` from `@liveblocks/react` directly. See https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details."
  );
  return _hooks.useSelf() as unknown as User<TPresence, TUserMeta> | null;
}

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useStorage` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useStorage<TStorage extends LsonObject>(): [
  root: LiveObject<TStorage> | null
] {
  deprecate(
    "Please use `createRoomContext()` instead of importing `useStorage` from `@liveblocks/react` directly. See https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details."
  );
  return _hooks.useStorage() as unknown as [root: LiveObject<TStorage> | null];
}

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useUndo` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useUndo(): () => void {
  deprecate(
    "Please use `createRoomContext()` instead of importing `useUndo` from `@liveblocks/react` directly. See https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details."
  );
  return _hooks.useUndo();
}

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useUpdateMyPresence` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useUpdateMyPresence<TPresence extends JsonObject>(): (
  overrides: Partial<TPresence>,
  options?: { addToHistory: boolean }
) => void {
  deprecate(
    "Please use `createRoomContext()` instead of importing `useUpdateMyPresence` from `@liveblocks/react` directly. See https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details."
  );
  return _hooks.useUpdateMyPresence() as unknown as (
    overrides: Partial<TPresence>,
    options?: { addToHistory: boolean }
  ) => void;
}

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useList` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useList<TValue extends Lson>(
  key: string
): LiveList<TValue> | null;

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useList` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useList<TValue extends Lson>(
  key: string,
  items: TValue[]
): LiveList<TValue> | null;

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useList` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useList<TValue extends Lson>(
  key: string,
  items?: TValue[] | undefined
): LiveList<TValue> | null {
  deprecate(
    "Please use `createRoomContext()` instead of importing `useList` from `@liveblocks/react` directly. See https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details."
  );
  return _hooks.useList_deprecated(key as any, items as any);
}

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useMap` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useMap<TKey extends string, TValue extends Lson>(
  key: string
): LiveMap<TKey, TValue> | null;

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useMap` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useMap<TKey extends string, TValue extends Lson>(
  key: string,
  entries: readonly (readonly [TKey, TValue])[] | null
): LiveMap<TKey, TValue> | null;

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useMap` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useMap<TKey extends string, TValue extends Lson>(
  key: string,
  entries?: readonly (readonly [TKey, TValue])[] | null | undefined
): LiveMap<TKey, TValue> | null {
  deprecate(
    "Please use `createRoomContext()` instead of importing `useMap` from `@liveblocks/react` directly. See https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details."
  );
  return _hooks.useMap_deprecated(key as any, entries as any);
}

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useObject` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useObject<TData extends LsonObject>(
  key: string
): LiveObject<TData> | null;

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useObject` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useObject<TData extends LsonObject>(
  key: string,
  initialData: TData
): LiveObject<TData> | null;

/**
 * @deprecated Please use `createRoomContext()` instead of importing
 * `useObject` from `@liveblocks/react` directly. See
 * https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details.
 */
export function useObject<TData extends LsonObject>(
  key: string,
  initialData?: TData
): LiveObject<TData> | null {
  deprecate(
    "Please use `createRoomContext()` instead of importing `useObject` from `@liveblocks/react` directly. See https://liveblocks.io/docs/guides/upgrading#upgrading-from-0-16-to-0-17 for details."
  );
  return _hooks.useObject_deprecated(key as any, initialData as any);
}
